# Generated by Django 3.2.9 on 2021-11-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0002_caught'),
    ]

    operations = [
        migrations.AddField(
            model_name='caught',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
