# Generated by Django 3.2.9 on 2021-11-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0003_caught_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='critter',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fossil',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gyroid',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
