# Generated by Django 3.2.9 on 2021-11-14 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0004_auto_20211114_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='order',
        ),
        migrations.RemoveField(
            model_name='fossil',
            name='order',
        ),
        migrations.RemoveField(
            model_name='gyroid',
            name='order',
        ),
        migrations.RemoveField(
            model_name='song',
            name='order',
        ),
    ]
